### ISSUE TITLE
ssl error when accessing with firefox

### ISSUE THREAD

**Issue by pourquoi42** [fjudith/docker-draw.io#2]
Hi,

I can't access the drawio app. Broser gives me an ssl error that i can not easily workaround

docker run -it --rm --name="draw" -p 8080:8080 fjudith/draw.io

firefox to -> https://localhost:8080/draw/?offline=1

=> 
````
Secure Connection Failed

An error occurred during a connection to localhost:8080. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
````

**Comment by fjudith** [comment]
Hello,

Draw.IO enforces https by default. It is currently recommended to put the application behind a Reverse-Proxy with SSL Offloading.
I'm currently using HAproxy 1.7.x to acheive this.

Otherwise, try to add `?https=0` as an URL parameter.

**Comment by davidjgraph** [comment]
Just to follow this up, we removed the https redirect recently in code, we're now forcing https at the CDN level.
