### ISSUE TITLE
Blank screen javascript error

### ISSUE THREAD

**Issue by gurpal2000** [fjudith/docker-draw.io#27]
On first run inside docker, i see a javascript error for offline mode.
If I remove offline=1, it works.

http://xxxxxxxxx:8280/?offline=1

(8080 -> 8280, no https)

app.min.js:8540
Uncaught ReferenceError: applicationCache is not defined
    at App.EditorUi.updateUi (app.min.js:8540)
    at new App (app.min.js:8931)
    at app.min.js:8942
    at app.min.js:194
    at mxXmlRequest.<anonymous> (app.min.js:276)
    at XMLHttpRequest.<anonymous> (app.min.js:179)

Using: fjudith/draw.io:latest@sha256:4f8bdbaebf7823e66e6289fea4df16093fbb365da1a4d8ab5abac2e82a7887c4

**Comment by fjudith** [comment]
hello @gurpal2000

i'm investigating to see if i can solve the issue at my level. but it seems to be an issue with draw. io app itself

**Comment by davidjgraph** [comment]
Offline=1 enables the appCache, I don't think that's what you want. It sounds like the appCache is disabled on that browser (cookies off does that). You want stealth=1 to block external connections.
