### ISSUE TITLE
GitLab custom URL not respected

### ISSUE THREAD

**Issue by science4reason** [fjudith/docker-draw.io#34]
I run docker-compose after cloning this repo. Draw.io starts and run on localhost:8080.
The docker log for draw.io display:
------
Init config.js
window.DRAWIO_GITLAB_URL = 'http://mygitlab.net';
window.DRAWIO_GITLAB_ID = 'change_to_your_app_id';
--------

Choosing Gitlab as target for storing files and selecting authorize. Still redirecting me to gitlab.com

**Comment by davidjgraph** [comment]
It's a known issue https://github.com/jgraph/drawio/issues/515
