### ISSUE TITLE
Option for "container" storage

### ISSUE THREAD

**Issue by thetomcorp** [fjudith/docker-draw.io#41]
would it be possible to add an option for "Container" storage. Using Device or Browser works well for individuals however it doesn't work well for collaboration. I'd like to have an instance of a DrawIO container running with a PersistentVolume or Docker Mount point so other users can connect to the instance and work on the same drawings with little configuration changes.

**Comment by davidjgraph** [comment]
These are still file systems, so selecting device is the right option, select the file system you want to save to.

**Comment by djmattyg007** [comment]
The point is to make it possible to store files server side.

**Comment by davidjgraph** [comment]
OK, but that's not an issue for this project. That's a task for the core project and one I think would be impossible to define.
