### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Buliwif** [fjudith/docker-draw.io#45]
Hi,

As a good newbie with Docker, I follow the steps to install/start it. I used "docker run -it --rm --name="draw" -p 8080:8080 -p 8443:8443 fjudith/draw.io"

Now I wish make French default langage but is there a way to include this parameter when running the pod ?
Someone would like to be a good teacher to me please ?

Thank You
Arno

**Comment by Buliwif** [comment]
I use e reverseproxy apache so I tried : 
    # RewriteEngine on
    # RewriteCond %{QUERY_STRING} !.+
    # RewriteRule “/(.+)?” “/$1local=1&lang=fr” [QSA,R]
But it doesn't Work ...

**Comment by Buliwif** [comment]
Finally i found a way with my reverse proxy.

**Comment by fjudith** [comment]
Great !  Can you share thé infos ?

**Comment by Buliwif** [comment]
Hi, sorry I was with my smartphone that's why my answer was quick :)
This work like a charm : 

    RewriteCond %{QUERY_STRING} !.+
    RewriteRule "/(.+)?" "/$1?local=1&lang=fr" [QSA,R]

Thank You for this really helpfull application.
Arno.
