### ISSUE TITLE
Missing Graphics for BPMN Gateways and BPMN Events when using offline mode

### ISSUE THREAD

**Issue by ramsonline** [fjudith/docker-draw.io#50]
I just started a new docker instance using the instructions -> docker run -it --rm --name="draw" -p 8080:8080 -p 8443:8443 fjudith/draw.io

i later stumbled upon missing graphics.

**BPMN Gateways and BPMN Events do only show white boxes in the left selection Menu**

Screenshot:
![grafik](https://user-images.githubusercontent.com/23153117/110091119-69e44280-7d98-11eb-96bb-c5c4dea48e14.png)

However those icons do appear when i no not use the offline parameter

**Comment by fjudith** [comment]
I guess this has been fixed by latest draw.io version
