### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by carukc** [fjudith/docker-draw.io#8]
Hello,

We have discovered a typo in your docker file that seems to be preventing the war/plugins/embed2js.patch from being included.

The Dockerfile should be :
> patch -p1 < war/plugins/embed2js.patch

but is: 
> patch -p1 war/plugins/embed2js.patch

Chris

**Comment by fjudith** [comment]
Hello,

Thank you for spotting this issue !

The patch is now applied successfully.

Florian
